import {
  AtSign,
  Brain,
  ChartNoAxesGantt,
  ChevronsLeftRightEllipsis,
  CircleUser,
  Computer,
  Container,
  Eye,
  FileCode2,
  FilePenLine,
  FileUser,
  FileVideo,
  Layers2,
  LayoutDashboard,
  Megaphone,
  MessageCircleMore,
  Radio,
  RouteOff,
  ScanSearch,
  Search,
  Send,
  TvMinimalPlay,
  User,
  Waypoints,
} from "lucide-react";

export const sidebarOptions = [
  {
    id: 2,
    title: "Manage Products",
    link: "/dashboard",
    submenus: [
      {
        id: 1,
        name: "Add Products",
        slug: "/dashboard/add-products",
        icons: <Eye size={16} />,
      },
      {
        id: 2,
        name: "Dashboard",
        slug: "/dasboard",
        icons: <LayoutDashboard size={16} />,
      },
      {
        id: 3,
        name: "Edit Your Profile",
        slug: "/dashboard/editProfile",
        icons: <FilePenLine size={16} />,
      },
      {
        id: 4,
        name: "Video CV",
        slug: "/dashboard",
        icons: <FileVideo size={16} />,
      },
      {
        id: 5,
        name: "Customized CV",
        slug: "/dashboard",
        icons: <FileCode2 size={16} />,
      },
      {
        id: 6,
        name: "Emailed CV",
        slug: "/dashboard",
        icons: <AtSign size={16} />,
      },
    ],
  },
  {
    id: 3,
    title: "Invitation",
    link: "/dashboard/addProduct",
    submenus: [
      {
        id: 1,
        name: "Live Interview",
        slug: "/dashboard",
        icons: <Radio />,
      },
      {
        id: 2,
        name: "Video Interview",
        slug: "/dashboard",
        icons: <TvMinimalPlay size={16} />,
      },
      {
        id: 3,
        name: "Genaral Interview",
        slug: "/dashboard",
        icons: <Container size={16} />,
      },
      {
        id: 4,
        name: "Online Test",
        slug: "/dashboard",
        icons: <Computer size={16} />,
      },
      {
        id: 5,
        name: "AI Assesment(viose Based)",
        slug: "/dashboard",
        icons: <Brain size={16} />,
      },
    ],
  },
  {
    id: 4,
    title: "My Activities",
    link: "/dashboard/messages",
    submenus: [
      {
        id: 1,
        name: "Applied Jobs",
        slug: "/dashboard/appliedJobs",
        icons: <FileUser size={16} />,
      },
      {
        id: 2,
        name: "Emailed Resume",
        slug: "/dashboard",
        icons: <Send size={16} />,
      },
      {
        id: 3,
        name: "Shortlisted Job",
        slug: "/dashboard",
        icons: <Layers2 size={16} />,
      },
      {
        id: 4,
        name: "Following Employer",
        slug: "/dashboard",
        icons: <CircleUser size={16} />,
      },
      {
        id: 5,
        name: "Transection Overview",
        slug: "/dashboard",
        icons: <ChartNoAxesGantt size={16} />,
      },
    ],
  },
  {
    id: 5,
    title: "Points & Rewords",
    link: "/dashboard/payment",
    submenus: [
      {
        id: 1,
        name: "My Points",
        slug: "/dashboard",
        icons: <Waypoints size={16} />,
      },
      {
        id: 2,
        name: "How do I earn points",
        slug: "/dashboard",
        icons: <RouteOff size={16} />,
      },
    ],
  },
  {
    id: 6,
    title: "Employer Activities",
    link: "/dashboard/settings",
    submenus: [
      {
        id: 1,
        name: "Employer Viewed CV",
        slug: "/dashboard",
        icons: <ScanSearch size={16} />,
      },
      {
        id: 2,
        name: "Employer Message",
        slug: "/dashboard",
        icons: <MessageCircleMore size={16} />,
      },
      {
        id: 3,
        name: "Employer Interested",
        slug: "/dashboard",
        icons: <ChevronsLeftRightEllipsis size={16} />,
      },
    ],
  },
  {
    id: 7,
    title: "Personalization",
    link: "/dashboard/profile",
    submenus: [
      {
        id: 1,
        name: "Favorite Search",
        slug: "/dashboard",
        icons: <Search size={16} />,
      },
      {
        id: 2,
        name: "SMS Job Alert",
        slug: "/dashboard",
        icons: <Megaphone size={16} />,
      },
      {
        id: 3,
        name: "My Training",
        slug: "/dashboard",
        icons: <User size={16} />,
      },
    ],
  },
];
